spring.application.name=job-portal-service
spring.datasource.url=jdbc:postgresql://localhost:5432/job_portal_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true